routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Input;

Route::get('/', function () {

    return view('welcome');
});


Auth::routes();

Route::group(['prefix' => 'webadmin', 'middleware' => ['webadmin']], function () {
    Route::get('/dashboard', 'admin\DashboardController@index');
    Route::get('/logout', 'Auth\LoginController@logout');
    Route::resource('/users', 'admin\UsersController');
    Route::resource('/admins', 'admin\AdminsController');
    Route::resource('/contacts', 'admin\ContactsController');
    Route::get('/contact/{id}/reply', 'admin\ContactsController@reply');
    Route::post('/contact/{id}/sendreply', 'admin\ContactsController@sendReply');
    Route::resource('/settings', 'admin\SettingController');
    Route::resource('/categories', 'admin\CategoriesController');
    Route::resource('/branches', 'admin\BranchesController');
    Route::resource('/advs', 'admin\AdvsController');
    Route::resource('/products', 'admin\ProductsController');
    Route::resource('/maintanenceRequests', 'admin\MaintanenceRequestsController');
    Route::resource('/choices', 'admin\ChoicesController');
    Route::resource('/priceRequests', 'admin\PriceRequestsController');
    Route::resource('/contracts', 'admin\ContractsController');
    Route::get('/priceAnswer/{id}', 'admin\PriceRequestsController@price_answer');
    Route::post('/priceAnswer/{id}/store', 'admin\PriceRequestsController@send_price');



});
Route::get('/getStates', function () {
    $city_id = Input::get('city_id');
    $states = \App\Models\State::where('city_id', '=', $city_id)->get();
    return json_encode($states);

});

app/Models/PriceRequest.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class PriceRequest extends Model
{
    protected $table = 'price_requests';
    protected $guarded = [];

    public $timestamps = true;
    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function choice()
    {
        return $this->belongsTo(Choice::class, 'choice_id');
    }
}

app/Http/Controllers/admin/PriceRequestsController.php
<?php

namespace App\Http\Controllers\admin;

use App\Models\PriceRequest;
use App\Notifications\PriceReplyNotification;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Notification;

class PriceRequestsController extends Controller
{
    public function index()
    {
        $priceRequests=PriceRequest::orderBy('created_at','ASC')->paginate(10);
        return view('admin.priceRequests.index',compact('priceRequests'));
    }



    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $priceRequest=PriceRequest::find($id);
        return view('admin.priceRequests.show',compact('priceRequest'));
    }
    public function price_answer($id)
    {
        $priceRequest=PriceRequest::find($id);
        return view('admin.priceRequests.reply',compact('priceRequest'));
    }
    public function send_price(Request $request,$id)
    {
        $request->validate([

            'price' => 'required',
        ]);
        $priceRequest=PriceRequest::find($id);
        $priceRequest->update([
            'answer'=>1,
            'price'=>$request->price,
            ]);

        //notification
        $user = User::find($priceRequest->user_id);
        $title = ' المصاعد';
        $content = 'الرد على طلب عرض السعر';
        $message = [
            'id' => $priceRequest->id,
            "price" => $request->price,

        ];
        Notification::send($user, new PriceReplyNotification($priceRequest));
        \Helpers::fcm_notification($user->device_token, $content, $title, $message);
        return redirect('/webadmin/priceRequests')->withFlashMessage(json_encode(['success'=>true,'msg'=>'تم الرد بالسعر بنجاح']));


    }





    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        PriceRequest::destroy($id);
        return redirect('/webadmin/priceRequests')->withFlashMessage(json_encode(['success'=>true,'msg'=>'تم حذف طلب عرض سعر بنجاح']));

    }
}

resources/views/admin/priceRequests/index.blade.php
@extends('admin.layouts.app')
@section('title')
    طلبات عرض سعر
@endsection

@section('header')
    {!! Html::style('admin/vendors/custom/datatables/datatables.bundle.rtl.css') !!}
@endsection

@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/priceRequests')}}" class="m-menu__link">
            <span class="m-menu__link-text">طلبات عرض سعر</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>


@endsection

@section('content')
    <div class="m-portlet m-portlet--mobile">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
                    <h3 class="m-portlet__head-text">
                        طلبات عرض سعر
                    </h3>
                </div>
            </div>
        </div>
        <div class="m-portlet__body">
            <br>
            {{--<div><a href="{{route('priceRequests.create')}}" style="margin-bottom:20px"--}}
                    {{--class="btn btn_primary btn btn-danger"><i class=" fa fa-edit"></i> اضف منتج</a></div>--}}
            <!--begin: Datatable -->
            <table class="table table-striped- table-bordered table-hover table-checkable search_result"
                   id="m_table_testArea">

                <thead>
                <tr>
                    <th>#</th>
                    <th>صاحب الطلب</th>
                    <th>الاسم بالكامل</th>
                    <th>رقم الجوال</th>
                    <th>العنوان</th>
                    <th>الاختيار</th>
                    <th>السعر</th>
                    <th>الاجراءات</th>
                </tr>
                </thead>
                <tbody>
                @foreach($priceRequests as $priceRequest)

                    <tr>
                        <td>{{$priceRequest->id}}</td>
                        <td><a href="/webadmin/users/{{$priceRequest->user_id}}">{{$priceRequest->user->name}}</a></td>
                        <td>{{$priceRequest->name}} </td>
                        <td>{{$priceRequest->phone}} </td>
                        <td>{{$priceRequest->address  }} </td>
                        <td>
                                <a href="/webadmin/choices/{{$priceRequest->choice_id}}">{{$priceRequest->choice_id}}</a><br>
                        </td>
                        <td>{{$priceRequest->price  }} </td>

                        <td>

                            <a  title="عرض التفاصيل" href="/webadmin/priceRequests/{{$priceRequest->id}}" ><i class="fa fa-eye"></i></a>
                            @if($priceRequest->answer==0)
                            <a  title="الرد بالسعر" href="/webadmin/priceAnswer/{{$priceRequest->id}}" ><i class="fa fa-reply"></i></a>
                            @endif
                            {{--<a title="Edit" href="/webadmin/priceRequests/{{$priceRequests->id}}/edit"><i--}}
                                    {{--class="fa fa-edit"></i></a>--}}
                            <form class="inline-form-style"
                                  action="/webadmin/priceRequests/{{ $priceRequest->id }}"
                                  method="post">
                                <button type="submit" class="trash-btn">
                                    <span class="fa fa-trash"></span>
                                </button>
                                <input type="hidden" name="_method" value="delete"/>
                                <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            </form>

                        </td>
                    </tr>
                @endforeach

                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('footer')
    {{--{!! Html::script('admin/vendors/custom/datatables/datatables.bundle.js') !!}--}}
    {{--{!! Html::script('admin/custom/js/testArea/script.js') !!}--}}

@endsection

resources/views/admin/priceRequests/reply.blade.php
@extends('admin.layouts.app')

@section('title')
    الرد بالسعر
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/categories')}}" class="m-menu__link">
            <span class="m-menu__link-text"> طلبات عرض سعر</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item" style="background: #e0deff;">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">الرد بالسعر</span>
            <i class="m-menu__hor-arrow la la-angle-down"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')

    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        الرد بالسعر
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        <form class="m-form m-form--fit m-form--label-align-right" action="/webadmin/priceAnswer/{{$priceRequest->id}}/store" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}

            <div class="m-portlet__body">
                <div class="form-group m-form__group row">
                    <label class="col-lg-2 col-form-label">السعر : </label>
                    <div class="col-lg-10{{ $errors->has('price') ? ' has-danger' : '' }}">
                        {!! Form::number('price',null,['class'=>'form-control m-input','autofocus','placeholder'=>"السعر"]) !!}
                        @if ($errors->has('price'))
                            <span class="form-control-feedback" role="alert">
                                <strong>{{ $errors->first('price') }}</strong>
                            </span>
                        @endif
                    </div>

                </div>
            </div>
            <div class="m-portlet__foot m-portlet__no-border m-portlet__foot--fit">
                <div class="m-form__actions m-form__actions--solid">
                    <div class="row">
                        <div class="col-lg-2"></div>
                        <div class="col-lg-6">
                            <button type="submit" class="btn btn-success">اضافة </button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
        <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection

resources/views/admin/priceRequests/show.blade.php
@extends('admin.layouts.app')

@section('title')
    تفاصيل طلب عرض سعر
@endsection
@section('topBar')
    <li class="m-menu__item">
        <a href="{{url('/webadmin/dashboard')}}" class="m-menu__link">
            <span class="m-menu__link-text">الرئيسية</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="{{url('/webadmin/priceRequests')}}" class="m-menu__link">
            <span class="m-menu__link-text">طلبات عرض سعر</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
    <li class="m-menu__item">
        <a href="" class="m-menu__link">
            <span class="m-menu__link-text">تفاصيل طلب عرض سعر</span>
            <i class="m-menu__hor-arrow la la-angle-left"></i>
        </a>
    </li>
@endsection

@section('header')
@endsection

@section('content')
    <!--begin::Portlet-->
    <div class="m-portlet">
        <div class="m-portlet__head">
            <div class="m-portlet__head-caption">
                <div class="m-portlet__head-title">
					<span class="m-portlet__head-icon m--hide">
						<i class="la la-gear"></i>
					</span>
                    <h3 class="m-portlet__head-text">
                        تفاصيل طلب عرض سعر
                    </h3>
                </div>
            </div>
        </div>
        <!--begin::Form-->
        {!! Form::model($priceRequest,['route' => ['priceRequests.show' , $priceRequest->id],'method'=> 'get','class'=>'m-form m-form--fit m-form--label-align-right',"enctype"=>"multipart/form-data"]) !!}
        <div class="m-portlet__body">


            <div class="form-group m-form__group row">
                <label class="col-lg-1 col-form-label">الاسم بالكامل </label>
                <div class="col-lg-5{{ $errors->has('name') ? ' has-danger' : '' }}">
                    {!! Form::text('name',old('name'),['class'=>'form-control m-input','autofocus','disabled' ]) !!}

                </div>
                <label class="col-lg-1 col-form-label">رقم الجوال</label>
                <div class="col-lg-5{{ $errors->has('phone') ? ' has-danger' : '' }}">
                    {!! Form::text('phone',old('phone'),['class'=>'form-control m-input','disabled' ]) !!}

                </div>


            </div>


            <div class="form-group m-form__group row">

                <label class="col-lg-2 col-form-label">العنوان</label>
                <div class="col-lg-10{{ $errors->has('service_type') ? ' has-danger' : '' }}">
                    <input type="text" class="form-control m-input" value="{{$priceRequest->address}}" disabled>

                </div>

            </div>
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">وصف الطلب</label>
                <div class="col-lg-10{{ $errors->has('details') ? ' has-danger' : '' }}">
                    {!! Form::textarea('details',old('details'),['class'=>'form-control m-input','disabled' ]) !!}

                </div>

            </div>
            <div class="form-group m-form__group row">
                <label class="col-lg-2 col-form-label">  منتجات الاختيار</label>
                <div class="col-lg-10{{ $errors->has('details') ? ' has-danger' : '' }}">
                    @foreach($priceRequest->choice->products as $product)
                        <a href="/webadmin/products/{{$product->id}}">{{$product->name}}</a><br>
                        @endforeach

                </div>



            </div>








        </div>

    {!! Form::close() !!}
    <!--end::Form-->
    </div>
    <!--end::Portlet-->
@endsection
@section('footer')
    <script type="text/javascript">

    </script>
@endsection